services:
  backend:
    build:
      dockerfile: slink/Dockerfile
      target: build-release-stage
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8060:8060
    environment:
      - BASE_URL=slink.augtheo.com
      - SERVER_PORT=8060
      - profile=prd
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - backend-db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-db
  slink-web:
    build:
      context: ./
      dockerfile: slink-web/dockerfile
    volumes:
      - /project/node_modules
    ports:
      - 5000:3000
    depends_on:
      - backend
  migrator:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}?sslmode=disable",
        "up",
      ]
    depends_on:
      - db
    networks:
      - backend-db
volumes:
  db-data:
networks:
  backend-db: {}
