FROM openapitools/openapi-generator-cli as gen
WORKDIR /workspace
COPY api/openapi.yaml ./api/openapi.yaml

RUN bash /usr/local/bin/docker-entrypoint.sh generate \
    -i /workspace/api/openapi.yaml \
    -g typescript-axios \
    -o generated \
    --additional-properties=supportsES6=true,typescriptThreePlus=true

FROM node:alpine as dev
WORKDIR /app

COPY slink-web/package.json /app/package.json
COPY slink-web/package-lock.json /app/package-lock.json
RUN npm install
COPY slink-web/ /app/
COPY --from=gen /workspace/generated /app/src/generated

# NOTE: It's not the end of the world if VITE_CLERK_PUBLISHABLE_KEY is commited
# TODO: Use a secret management tool to fetch secrets before building

ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_APP_API_URL

RUN echo "VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}" >> /app/.env
RUN echo "VITE_APP_API_URL=${VITE_APP_API_URL}" >> /app/.env

EXPOSE 3000

ENTRYPOINT [ "npm", "run" , "dev" ]


FROM dev AS build
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY slink-web/nginx.conf /etc/nginx/conf.d/default.conf
