FROM node:alpine as dev
WORKDIR /app

COPY slink-web/package.json /app/package.json
COPY slink-web/package-lock.json /app/package-lock.json
RUN npm install
COPY slink-web/ /app/

EXPOSE 3000

ENTRYPOINT [ "npm", "run" , "dev" ]


FROM dev AS build
RUN npm run build

FROM nginx:alpine AS prod
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY slink-web/nginx.conf /etc/nginx/conf.d/default.conf
